config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  get '/user/profile',  to: 'users#show', as: 'user_profile'
  get '/s', to: 'rooms#search'
  resources :rooms do
    resources :bookings, only: [ :new, :create ]
  end
  #resources :bookings
  resources :ratings

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
  #has_attachment  :avatar, accept: [:jpg, :png, :gif]
  #has_attachments :photos, maximum: 10

    #validates :avatar, presence: true

  has_many :rooms, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # facebook stuff copy pasted from slides
  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def update
    @user = User.find(params[:id])
    if params[:user]
      @user.update(user_params)
    end
      redirect_to user_path
  end

  def show
    @user = current_user
    @rooms = @user.rooms
    @bookings = @user.bookings
  end


private
  def user_params
    params.require(:user).permit(:avatar, :bio, :location)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/bookings.html.erb
<h1>Users#bookings</h1>
<p>Find me in app/views/users/bookings.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div style="width: 70%; margin: 0 auto;">
  <h1>Profile</h1>
  <div class="bordered margined">
    <h3><%= @user.first_name + " " + @user.last_name%></h3>
    <p><%= @user.email %></p>
    <p><%= @user.phone_number %></p>
  </div>
  <div class="bordered margined">
    <%= link_to new_room_path, class: "btn btn-primary" do %>
      <h6>New Room</h6>
    <% end %>
  </div>
  <% if @bookings.length > 0 %>
  <h2>Bookings</h2>
  <% end %>
  <% @bookings.each do |booking| %>
  <div class="bordered row margined" >
    <div class="col-md-3 justified">
    <h6><%= booking.room.name %></h6>
    </div>
    <div class="col-md-9 justified">
      <div class="col-md-6">
        <p>Start Date: <strong><%= booking.start_date %></strong></p>
        <p>End Date: <strong><%= booking.end_date %></strong></p>
        <p>Price: <strong><%= booking.price %></strong></p>
        <p>People: <strong><%= booking.num_of_persons %></strong></p>
      </div>
      <div class="col-md-6">
        <%= cl_image_tag booking.room.photos.first.path, width: 200, height: 200, crop: :fill %>
      </div>
    </div>
  </div>
  <% end %>
  <% if @rooms.length > 0 %>
  <h2>Rooms</h2>
  <% end %>
  <% @rooms.each do |room| %>
  <div class="bordered row margined" >
    <div class="col-md-3 justified">
    <%= link_to edit_room_path(room) do %>
      <h3><%= room.name %></h3>
    <% end %>

    </div>
    <div class="col-md-9 justified">
      <div class="col-md-6">
        <p>Address: <strong><%= room.address %></strong></p>
        <p>Accomodate: <strong><%= room.accomodate %></strong></p>
        <p>Home Type: <strong><%= room.home_type %></strong></p>
        <p>Room Type: <strong><%= room.room_type %></strong></p>
      </div>
      <div class="col-md-6">
        <%= cl_image_tag room.photos.first.path, width: 200, height: 200, crop: :fill %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>