config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  get '/user/profile',  to: 'users#show', as: 'user_profile'
  get '/s', to: 'rooms#search'
  resources :rooms do
    resources :bookings, only: [ :new, :create ]
  end
  #resources :bookings
  resources :ratings

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer-social.html.erb
<div class="footer-social-links-wrapper">
  <div class="footer-social-links-container">
    <a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a>
    <a href="https://www.github.com"><i class="fa fa-github"></i></a>
    <a href="https://www.twitter.com"><i class="fa fa-twitter"></i></a>
    <a href="https://www.instagram.com"><i class="fa fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-social-links-wrapper" id="show-view-footer">
  <div class="footer-social-links-container">
    <a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a>
    <a href="https://www.github.com"><i class="fa fa-github"></i></a>
    <a href="https://www.twitter.com"><i class="fa fa-twitter"></i></a>
    <a href="https://www.instagram.com"><i class="fa fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Left Navigation -->
  <div class="navbar-wagon-left">
    <!-- Logo linking home -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>
    <!-- Search form -->
      <form action="/s" method="get" class="navbar-wagon-search">
          <input type="search" class="navbar-wagon-search-input" name="address" id="address" class="form-control search-row" placeholder="Where are we going?" />
          <button class="btn hidden" type="submit"></button>
    </form>



  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <!-- Notifications -->
        <a href="" class="text-center">
          <div class="badge-container">
          </div>
        </a>

      <!-- Profile picture and dropdown for whatever we want -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

  <!-- Standard display of login and sign in links -->

      <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link text-center" %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link text-center" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <% if user_signed_in? %>
        <li>
          <%= link_to user_profile_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      <% else %>
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(".sign_up", default: "Sign In"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/places.js/1/places.min.js"></script>
<script>
  (function() {
    var placesAutocomplete = places({
      container: document.querySelector('#address')
    });

    var $address = document.querySelector('#address-value')
    placesAutocomplete.on('change', function(e) {
      $address.textContent = e.suggestion.value
    });

    placesAutocomplete.on('clear', function() {
      $address.textContent = 'none';
    });

  })();
</script>