config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  get '/user/profile',  to: 'users#show', as: 'user_profile'
  get '/s', to: 'rooms#search'
  resources :rooms do
    resources :bookings, only: [ :new, :create ]
  end
  #resources :bookings
  resources :ratings

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  attr_accessor :start_date
  attr_accessor :end_date
  attr_accessor :price
  belongs_to :user
  has_many :booking_slots, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, :home_type, :room_type, :accomodate, :bedrooms, :bathrooms, :summary, :address, presence: true
  validates :summary, length: {maximum: 500}
  validates :name, length: {maximum: 100}

  has_attachments :photos, maximum: 10
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
# User must be authneticated before every controller action, except for show
  before_action :authenticate_user!, except: [:show]


  def new
    @room = Room.new
  end

  def show
    @booking = Booking.new
    @room = Room.find(params[:id])
    @alert_message = "You are viewing #{@room.name}"

    @photos = @room.photos

    @reviews = @room.reviews
    @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def search
    if Room.near(params[:address], 1000).empty?
      notice
      redirect_to rooms_path, alert: "No results found! Please search again."
    else
      @rooms = Room.near(params[:address], 500)
      flash[:notice] =  "#{@rooms.length} results found!"

    end
    @hash = Gmaps4rails.build_markers(@rooms) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      marker.infowindow flat.name
    end
  end

  def index
    @rooms = current_user.rooms
    @rooms = Room.where.not(latitude: nil, longitude: nil)
    @hash = Gmaps4rails.build_markers(@rooms) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
      marker.infowindow flat.name
    end
  end

  def create
    raise
    @room = current_user.rooms.build(room_params)
    if params[:room][:start_date].length == 0 || params[:room][:end_date].length == 0
      render :new, alert: "Insert dates."
      return
    end
    day = datepicker_to_date(params[:room][:start_date])
    end_date = datepicker_to_date(params[:room][:end_date])
    if day < end_date
      render :new, alert: "Choose correct dates."
      return
    end
    price = params[:room][:price]
    if @room.save && day < end_date
      if params[:images]
        params[:images].each do |image|
          @room.photo.create(image: image)
        end
      end
      @photos = @room.photos
      while !(day === end_date)
        slot = BookingSlot.new(date: day.to_s(:db), day_price: price)
        slot.room = @room
        slot.save!
        day = day + 1
      end
      redirect_to user_profile_path, notice: "Saved Room."
    else
      render :new, alert: "Room not saved."
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |image|
          @room.photo.create(image: image)
        end
      end
      redirect_to user_profile_path, notice: "Room updated successfully."
  end
end
  def edit
    if current_user.id == @room.user.id
      @photos = @room.photo
    else
      redirect_to :index, notice: "You can't make changes to this room."
    end
  end

  private

  def set_room
  @room = Room.find(params[:id])
  end

  def room_params
  params.require(:room).permit(
  :name, :home_type, :room_type, :accomodate, :description,
  :bedrooms, :bathrooms, :summary, :address, :has_tv,
  :has_wifi, :has_kitchen, :has_heating, :has_aircon, :price, :activate, :photo_cache, :url, photos: [] )
  end

  def datepicker_to_date(datepicker_string)
    Date.strptime(datepicker_string.gsub('/','-'), '%d-%m-%Y')
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_booking-form.html.erb
<div class="booking-form-container" id="booking-form">
  <div class="booking-price-display">
    <h6><strong><%= @room.booking_slots.first.day_price.to_i %>$ per Night</strong></h6>
  </div>
  <div class="booking-form">
    <%= simple_form_for @booking , url: room_bookings_path(@room), :method => :post do |f| %>
      <%= f.input :start_date, as: :string, input_html: { id: 'booking-start-datepicker' }, class: "booking-form-input" %>
      <%= f.input :end_date, as: :string, input_html: { id: 'booking-end-datepicker' }, class: "booking-form-input" %>
      <%= f.input :num_of_persons, collection: 1..@room.accomodate, class: "booking-form-input" %>
      <%= f.submit "Book", class: "btn btn-primary", id: "book-btn" %>
    <% end %>
  </div>
</div>
<% content_for(:after_js) do %>
  <script>
    var available_days = [];
    <% @room.booking_slots.each do |s| %>
      <% if s.booking == nil %>
        available_days.push(new Date(<%= s.date.year %>, <%= s.date.month - 1 %>, <%= s.date.day %>));
      <% end %>
    <% end %>
    function isSameDay(day1, day2){
      return (day1.getFullYear() == day2.getFullYear() && day1.getMonth() == day2.getMonth() && day1.getDate() == day2.getDate())
    }
    $(document).ready(function(){
      $('#booking-start-datepicker').datepicker({
        dateFormat: "dd/mm/yy",
        beforeShowDay: function(date) {
          for(var i=0; i<available_days.length; i++) {
            if(isSameDay(date, available_days[i])){
              return [true, ''];
            }
          }
          return [false, ''];
        },
        onSelect: function(date) {
          $('#booking-end-datepicker').datepicker( "option", "minDate", date);
        },
        minDate: new Date()
      });
      $('#booking-end-datepicker').datepicker({
        dateFormat: "dd/mm/yy",
        beforeShowDay: function(date) {
          for(var i=0; i<available_days.length; i++) {
            if(isSameDay(date, available_days[i])){
              return [true, ''];
            }
          }
          return [false, ''];
        },
        minDate: new Date()
      });
    });

  </script>
<% end %>

app/views/rooms/_home-card.html.erb
<div class="user-container">
  <div class="avatar-container">
    <div class="avatar-large">
    </div>
  </div>
  <div class="name">
  </div>
</div>

<div class="info-container padded">
  <div class="avatar-container col-md-3 text-center">
    <div class="avatar-large">
      <img class="avatar-large" id="navbar-wagon-menu"  src="<%= @room.user.facebook_picture_url%>" alt="Picture?type=square">
      <a href=""><h6><%= @room.user.first_name %></h6></a>
    </div>
  </div>
  <div class="col-md-9">
    <div class="display-name-address">
      <h3><%= @room.name %></h3>
      <div class="display-address list-inline">
        <li>
          <a href="" class="address-link"><h6><%= @room.address %></h6></a>
        </li>
        <li>
          <%= render 'reviews-stars' %>
        </li>
    </div>
    </div>
    <div class="display-details list-inline text-center">
        <li>
          <div class="fa fa-building display-icons"></div>
          <h6><%= @room.home_type.capitalize %></h6>
        </li>
        <li>
          <div class="fa fa-users display-icons"></div>
          <h6><%= @room.accomodate %> pax</h6>
        </li>
        <li>
          <div class="fa fa-home display-icons"></div>
          <h6><%= @room.room_type.capitalize %></h6>
        </li>
        <li>
          <div class="fa fa-bed display-icons"></div>
          <h6><%= @room.accomodate %>beds</h6>
        </li>
    </div>
  </div>
</div>

app/views/rooms/_listing-details.html.erb
<div class="bordered row" data-react="overview">
  <div class="col-lg-8">
    <div class="margined">
      <h3>About this property</h3>
      <div>
        <p><%= @room.description %></p>
      </div>
    </div>
  </div>
</div>

<div class="bordered row margined" >
  <div class="col-md-3 justified">
    <h6>The space</h6>
  </div>
  <div class="col-md-9 justified">
    <div class="col-md-6">
      <p>Accommodates: <strong><%= @room.accomodate %></strong></p>
      <p>Bathrooms: <strong><%= @room.bathrooms %></strong></p>
      <p>Bedrooms: <strong><%= @room.bedrooms %></strong></p>
      <p>Beds: <strong><%= @room.accomodate %></strong></p>
    </div>
    <div class="col-md-6">
      <p>Check In: <strong>1PM</strong></p>
      <p>Check Out: <strong>11AM</strong></p>
      <p>Property type: <strong><%= @room.home_type %></strong></p>
      <p>Room type: <strong><%= @room.room_type %></strong></p>
    </div>
  </div>
</div>


<div class="bordered row margined " >
  <div class="col-md-3 justified">
    <h6>Amenities</h6>
  </div>
  <div class="col-md-9 justifed">
    <div class="col-md-6 justified">
      <% if @room.has_wifi %>
        <div class="fa fa-wifi display-icons-small text-center" id="has_wifi"><h6>Wi-Fi</h6></div>
      <% end %>
      <% if @room.has_kitchen %>
        <div class="fa fa-cutlery display-icons-small text-center" id="has_kitchen"><h6>Kitchen</h6></div>
      <% end %>
      <% if @room.has_aircon %>
        <div class="fa fa-snowflake-o display-icons-small text-center" id="has_aircon"><h6>Air Conditioning</h6></div>
      <% end %>
      <% if @room.has_heating %>
        <div class="fa fa-sun-o display-icons-small text-center" id="has_heating"><h6>Heating</h6></div>
      <% end %>
      <% if @room.has_tv %>
        <div class="fa fa-television display-icons-small text-center" id="has_tv"><h6>TV</h6></div>
      <% end %>
    </div>
  </div>
</div>


<div class="bordered row margined " >
    <div class="col-md-3 justified">
      <h6>Prices</h6>
    </div>
    <div class="col-md-9 justifed">
      <p>per/day:<strong><%= @room.booking_slots.first.day_price %>$</strong></p>
    </div>
</div>


<div class="row margined " >
    <div class="col-md-3 justified">
      <h6>Description</h6>
    </div>
    <div class="col-md-9 justifed">
      <p><%= @room.summary %></p>
    </div>
</div>

app/views/rooms/_review-stars-for-review-card.html.erb
<ul class="list-inline">
  <li><p><strong><%= review.created_at.strftime("%B %d, %Y") %></strong></p></li>
  <li>
    <ul class="list-inline">
      <% review.star.times do %>
      <li class="fa fa-star star star-active"></li>
      <% end %>
      <% (5 - review.star.round).times do %>
      <li class="fa fa-star star"></li>
      <% end %>
      <% case review.star %>
        <% when 1 %>
        <li>Poor</li>
        <% when 2 %>
        <li>Below Average</li>
        <% when 3 %>
        <li>Average</li>
        <% when 4 %>
        <li>Good</li>
        <% when 5 %>
        <li>Excellent</li>
      <% end %>
    </ul>
  </li>
</ul>

app/views/rooms/_review-stars-for-room-card.html.erb
<%= link_to room_path(room.id, anchor:  "reviews"), id:"reviews-average" do %>
  <ul class="list-inline">
    <% room.reviews.average(:star).to_i.round.times do %>
    <li class="fa fa-star star star-active"></li>
    <% end %>
    <% (5 - room.reviews.average(:star).to_i.round).times do %>
    <li class="fa fa-star star"></li>
    <% end %>
    <li><p class="review-count">(<%= room.reviews.count %>) Reviews</p></li>
  </ul>
<% end %>

app/views/rooms/_reviews-show.html.erb
<div class="bordered row">
  <div class="col-lg-8">
    <div class="title-margins">
      <strong><%= render 'reviews-stars' %></strong>
    </div>
  </div>
</div>


<% @room.reviews.each do |review| %>
<div class="row margined bordered">
  <div class="avatar-container col-md-3 text-center">
    <div class="avatar-large">
      <img class="avatar-large" id="navbar-wagon-menu"  src="<%= review.user.facebook_picture_url %>" alt="Picture?type=square">
      <a href=""><h6><%= review.user.first_name %></h6></a>
    </div>
  </div>
    <div class="col-md-9 justifed padded">
      <p><%= review.description %></p>
      <p><%= render 'review-stars-for-review-card', :review => review %></p>
    </div>
</div>
<% end %>

app/views/rooms/_reviews-stars.html.erb
<%= link_to room_path(@room.id, anchor:  "reviews"), id:"reviews-average" do %>
  <ul class="list-inline">
    <% @room.reviews.average(:star).to_i.round.times do %>
    <li class="fa fa-star star star-active"></li>
    <% end %>
    <% (5 - @room.reviews.average(:star).to_i.round).times do %>
    <li class="fa fa-star star"></li>
    <% end %>
    <li>(<%= @room.reviews.count %>) Reviews</li>
  </ul>
<% end %>

app/views/rooms/_room_card.html.erb
<%= link_to room_path(room.id), class: "card-link" do %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path room.photos.first.path, height: 300, width: 400, crop: :fill %>')">
  </div>
<% end %>
<div class="card-details">
  <ul class="list-inline">
    <li>
      <p>
        <strong>
        <%= room.booking_slots.first.day_price.to_i %>$/night -
          <%= link_to room_path(room.id, anchor: "overview"), class: "card-name" do %>
            <%= room.name %>
          <% end %>
        </strong>
      </p>
    </li>
    <li>
      <%= render 'rooms/review-stars-for-room-card', :room => room  %>
      </li>
  </ul>
  <%= link_to room_path(room.id, anchor:  "map"), class: "card-address" do %>
    <p><%= room.address %></p>
  <% end %>
</div>

app/views/rooms/_tabs.html.erb
<div class="tabs">
  <%= link_to room_path(@room.id, anchor:  "overview"), class: "tab active" do %>
    <h2>Overview</h2>
  <% end %>
  <%= link_to room_path(@room.id, anchor:  "reviews"), class: "tab" do %>
    <h2>Reviews</h2>
  <% end %>
  <%= link_to room_path(@room.id, anchor:  "map"), class: "tab" do %>
    <h2>Location</h2>
  <% end %>
  <%= link_to room_path(@room.id, anchor:  "show-photos"), class: "tab" do %>
    <h2>Photos</h2>
  <% end %>
</div>

<script>
  $(function(){
    $(".tab").on("click", function(e){
      // Change active tab
      $(".tab").removeClass('active');
      $(this).addClass('active');
    });
  });
</script>

<!-- anchor: directs to a a div with id specified -->

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/index.html.erb
<div class="results-wrapper">
  <div class="row results-row">
    <div class="col-xs-12 col-lg-6 results-container">
    <div class="row cards-row">
      <div class="col-log-6 results-found">
        <p><%= @rooms.length %> results found!</p>
      </div>
    </div>
      <div class="row cards-row">
        <% @rooms.each do |room| %>
          <div class="col-lg-6 card-container">
            <%= render 'room_card', :room => room %>
          </div>
        <% end  %>
      </div>
    </div>
    <div class="col-lg-6 map-column">
      <div id="map" class="map"></div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>



<%= content_for(:after_js) do %>
<script>
  $(document).ready(function() {
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  });
</script>
<% end %>

app/views/rooms/new.html.erb
<div style="width: 70%; margin: 0 auto;">
<h1>New Room</h1>
<%= simple_form_for @room do |f| %>
  <%= f.input :name %>
  <%= f.input :home_type %>
  <%= f.input :room_type %>
  <%= f.input :accomodate, as: :integer, input_html: { min: '0'}%>
  <%= f.input :bedrooms, as: :integer, input_html: { min: '0'}%>
  <%= f.input :bathrooms, as: :integer, input_html: { min: '0'}%>
  <%= f.input :summary, as: :text %>
  <%= f.input :description, as: :text %>
  <%= f.input :address %>
  <%= f.input :has_tv %>
  <%= f.input :has_wifi %>
  <%= f.input :has_kitchen %>
  <%= f.input :has_heating %>
  <%= f.input :has_aircon %>
  <%= f.input :activate %>
  <%= f.input :start_date, as: :string, input_html: { class: 'datepicker' } %>
  <%= f.input :end_date, as: :string, input_html: { class: 'datepicker' } %>
  <%= f.input :price, as: :integer, input_html: { min: '0'} %>
  <%= f.input :photos, as: :attachinary %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>
</div>

app/views/rooms/search.html.erb
<div class="results-wrapper">
  <div class="row results-row">
    <div class="col-xs-12 col-lg-6 results-container">
    <div class="row cards-row">
      <div class="col-log-6 results-found">
        <p><%= @rooms.length %> results found!</p>
      </div>
    </div>
      <div class="row cards-row">
        <% @rooms.each do |room| %>
          <div class="col-lg-6 card-container">
            <%= render 'room_card', :room => room %>
          </div>
        <% end  %>
      </div>
    </div>
    <div class="col-lg-6 map-column">
      <div id="map" class="map"></div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>



<%= content_for(:after_js) do %>
<script>
  $(document).ready(function() {
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  });
</script>
<% end %>

app/views/rooms/show.html.erb
<div class="show-banner" id="show-photos">
<% cl_img = "http://res.cloudinary.com/dod0sl861/image/upload/" %>
<% @room.photos.each do |p| %>
<a href="<%= "#{cl_img}#{p.path}" %>" data-lightbox="pics" class="banner">
      <%= cl_image_tag p.path, alt: "image" %>
      </a>
<% end %>
    <%# end %>
</div>

  <div class="wrapper" id="getFixed">
    <div class="container" id="tabs-booking-container">
      <div class="row" >
        <div class="col-lg-8">
          <div class="row hide-md" id="tabs-booking-row">
            <div class="row bordered">
              <%= render 'tabs'  %>
            </div>
            <div class="row bordered">
              <%= render 'home-card' %>
            </div>
          </div>
        </div>
        <div class="col-lg-4 column">
          <%= render 'booking-form'  %>
        </div>
      </div>
  </div>
</div>
  <div class="container">
    <div class="row" id="overview">
      <div class="col-lg-8">
          <%= render 'listing-details' %>
      </div>
    </div>
  </div>
  <div class="full-width-border"></div>
  <div class="container">
    <div class="row" id="reviews">
      <div class="col-lg-8">
          <%= render 'reviews-show' %>
      </div>
    </div>

  </div>




<div id="map" style="width: 100%; height: 400px;"></div>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function() {
    var myLatLng = {lat: <%= @room.latitude.to_f %>, lng: <%= @room.longitude.to_f %>};
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
      markers = handler.addMarker(myLatLng);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(13);
    });
  });
  jQuery(function($) {
  function fixDiv() {
    var $cache = $('#getFixed');
    if ($(window).scrollTop() > 700)
      $cache.css({
        'position': 'fixed',
        'top': '0',
        'background-color': 'white',
        'z-index': '1',
        'width': '100%'
      });
    else
      $cache.css({
        'position': 'relative',
        'top': 'auto'
      });
    }
      $(window).scroll(fixDiv);
      fixDiv();
  });
</script>
  <% end %>